version: '3'
services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=koala
            - MYSQL_ROOT_PASSWORD=db_koala
        ports:
            - '127.0.0.1:3310:3306'
        volumes:
            - mysql:/var/lib/mysql
    apache:
        image: pswerlang/php-apache
        restart: always
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html
volumes:
    mysql: